# Generated by Django 4.0.5 on 2022-07-06 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0002_user_c'),
    ]

    operations = [
        migrations.DeleteModel(
            name='user_c',
        ),
    ]
