# Generated by Django 4.0.5 on 2022-07-06 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_delete_user_c'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name',
            new_name='name_user',
        ),
    ]
