# Generated by Django 4.0.5 on 2022-07-06 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_rename_name_movie_name_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='name_user',
            new_name='name',
        ),
    ]
