# Generated by Django 4.0.5 on 2022-07-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_rename_name_user_movie_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='burget',
            field=models.IntegerField(default=1000000),
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
