# Generated by Django 4.0.5 on 2022-07-07 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0014_actor_movie_actor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='actor',
            new_name='actors',
        ),
    ]
